-- SCP Pocket EA - initial schema
-- Generated by hand from src/db/schema.ts to allow no-local-tools deployment.
-- Idempotent: uses IF NOT EXISTS everywhere.

-- ===== Enums =====
DO $$ BEGIN
  CREATE TYPE catalogue_kind AS ENUM ('material', 'service', 'labour', 'callout');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE job_status AS ENUM ('in_progress', 'completed', 'invoiced', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE invoice_status AS ENUM ('draft', 'sent_to_admin', 'pushed_to_xero', 'paid', 'void');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- ===== NextAuth tables =====
CREATE TABLE IF NOT EXISTS "user" (
  id text PRIMARY KEY,
  name text,
  email text NOT NULL UNIQUE,
  "emailVerified" timestamp,
  image text,
  role text NOT NULL DEFAULT 'operator'
);

CREATE TABLE IF NOT EXISTS account (
  "userId" text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  type text NOT NULL,
  provider text NOT NULL,
  "providerAccountId" text NOT NULL,
  refresh_token text,
  access_token text,
  expires_at integer,
  token_type text,
  scope text,
  id_token text,
  session_state text,
  PRIMARY KEY (provider, "providerAccountId")
);

CREATE TABLE IF NOT EXISTS session (
  "sessionToken" text PRIMARY KEY,
  "userId" text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  expires timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "verificationToken" (
  identifier text NOT NULL,
  token text NOT NULL,
  expires timestamp NOT NULL,
  PRIMARY KEY (identifier, token)
);

-- ===== Business =====
CREATE TABLE IF NOT EXISTS settings (
  id integer PRIMARY KEY DEFAULT 1,
  business_name text NOT NULL DEFAULT 'Shane Collins Plumbing',
  abn text NOT NULL DEFAULT '36 203 735 053',
  gst_registered boolean NOT NULL DEFAULT true,
  licence_number text DEFAULT '',
  address_line text NOT NULL DEFAULT 'Byron Bay NSW 2481',
  phone text DEFAULT '',
  email text DEFAULT '',
  bank_account_name text DEFAULT '',
  bank_bsb text DEFAULT '',
  bank_account_number text DEFAULT '',
  default_hourly_rate numeric(10,2) NOT NULL DEFAULT 140.00,
  default_callout_fee numeric(10,2) NOT NULL DEFAULT 120.00,
  payment_terms_days integer NOT NULL DEFAULT 7,
  gst_inclusive boolean NOT NULL DEFAULT false,
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS customer (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text,
  phone text,
  address text,
  notes text,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS catalogue (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  kind catalogue_kind NOT NULL DEFAULT 'material',
  unit text NOT NULL DEFAULT 'each',
  price_ex_gst numeric(10,2) NOT NULL,
  gst_applies boolean NOT NULL DEFAULT true,
  aliases text[] NOT NULL DEFAULT '{}',
  active boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS job (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id uuid REFERENCES customer(id),
  customer_name_snapshot text NOT NULL,
  address_snapshot text NOT NULL,
  arrived_at timestamp NOT NULL DEFAULT NOW(),
  left_at timestamp,
  arrived_gps jsonb,
  left_gps jsonb,
  initial_note text,
  voice_transcript text,
  voice_duration_sec integer,
  status job_status NOT NULL DEFAULT 'in_progress',
  created_by text REFERENCES "user"(id),
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS photo (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  blob_url text NOT NULL,
  caption text,
  taken_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS invoice (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id uuid REFERENCES job(id) ON DELETE SET NULL,
  customer_id uuid REFERENCES customer(id),
  customer_name_snapshot text NOT NULL,
  address_snapshot text NOT NULL,
  invoice_number text,
  issue_date timestamp NOT NULL DEFAULT NOW(),
  due_date timestamp NOT NULL,
  subtotal_ex_gst numeric(10,2) NOT NULL,
  gst_amount numeric(10,2) NOT NULL,
  total_inc_gst numeric(10,2) NOT NULL,
  notes text,
  extraction_notes text,
  status invoice_status NOT NULL DEFAULT 'draft',
  sent_at timestamp,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS invoice_line (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL REFERENCES invoice(id) ON DELETE CASCADE,
  position integer NOT NULL DEFAULT 0,
  catalogue_id uuid REFERENCES catalogue(id),
  description text NOT NULL,
  quantity numeric(10,2) NOT NULL,
  unit text NOT NULL DEFAULT 'each',
  unit_price_ex_gst numeric(10,2) NOT NULL,
  gst_applies boolean NOT NULL DEFAULT true,
  line_total_ex_gst numeric(10,2) NOT NULL
);

-- Ensure pgcrypto extension for gen_random_uuid (usually present on Neon)
CREATE EXTENSION IF NOT EXISTS pgcrypto;
